name: diff
on: 
  pull_request

jobs:
  get-diff:
      runs-on: ubuntu-latest
      name: Get Diff
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: git diff
          run: | 
            echo 'start'
            echo "DIFF<<END_OF_DIFF" >> ${GITHUB_ENV}
            echo "DIFF=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | base64) END_OF_DIFF" >> ${GITHUB_ENV}
            echo "END_OF_DIFF" >> ${GITHUB_ENV}
            echo 'aa'
        - name: use diff
          run: echo 'aaa'
