name: diff
on: 
  pull_request

jobs:
  get-diff:
      runs-on: ubuntu-latest
      name: Get Diff
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: git diff
          run: echo $(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}) | base64 >> $GITHUB_OUTPUT
        - name: use diff
          run: echo "${{ steps.tests.outputs.stdout }}"
