name: diff
on: 
  pull_request

jobs:
  get-diff:
      runs-on: ubuntu-latest
      name: Get Diff
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: git diff
          run: | 
            echo "DIFF<<END_OF_DIFF" >> ${GITHUB_ENV}
            echo "DIFF=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})" >> ${GITHUB_ENV}
            echo "END_OF_DIFF" >> ${GITHUB_ENV}
        - name: use diff
          run: | 
            echo $DIFF
  store-diff:
      runs-on: ubuntu-latest
      name: Get Diff and store in diff.txt
      steps:
       - name: Checkout
         id: checkout_2
         uses: actions/checkout@v4
         with:
            fetch-depth: 2
       - name: git diff to file
         run: | 
           $(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}) > diff.txt
       - name: Upload math result for job 1
         uses: actions/upload-artifact@v4
         with:
           name: diff
           path: diff.txt
